[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"
via_ir = true

fs_permissions = [
  { access = "read-write", path = "./broadcast_out" }
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"


